services:
  - type: web
    name: landver
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ETHEREUM_RPC_URL
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: LAND_REGISTRY_CONTRACT_ADDRESS
        sync: false