[package]
name = "landver"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html


[workspace]
members = ["land_registry/*"]

[workspace.package]
description = "Land Registry."
cairo-version = "2.8.2"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/NoshonNetworks/landver"
license-file = "LICENSE"

[workspace.dependencies]
cairo_test = "2.8.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.17.0" }
starknet = ">=2.8.0"

[[target.starknet-contract]]
